irc_token = 'oauth:'
client_id = ''
client_secret = ''
nick = 'LogicEFTBot'
prefix = '!'
initial_channels = ['LogicalSolutions','WillerZ','lvndmark']
default_cooldown = 10
default_lang = 'en'
slot_link_en = ''
ammo_link_en = ''
price_link_en = ''
wiki_link_en = ''
medical_link_en = ''
trader_link_en  = ''
slot_link_es = ''
ammo_link_es = ''
price_link_es = ''
wiki_link_es = ''
medical_link_es = ''
trader_link_es  = ''
slot_link_de = ''
ammo_link_de = ''
price_link_de = ''
wiki_link_de = ''
medical_link_de = ''
trader_link_de  = ''
slot_link_tr = ''
ammo_link_tr = ''
price_link_tr = ''
wiki_link_tr = ''
medical_link_tr = ''
trader_link_tr  = ''
slot_link_ru = ''
ammo_link_ru = ''
price_link_ru = ''
wiki_link_ru = ''
medical_link_ru = ''
trader_link_ru  = ''
database_config = {
    'host': 'localhost',
    'user': 'root',
    'passwd': '',
    'database': ''
}
